import type { ProjectType } from "./types"

export const mockProjects: ProjectType[] = [
  {
    id: "1",
    title: "Product Roadmap 2025",
    description: "Strategic product roadmap for the upcoming year with key milestones and deliverables",
    type: "whiteboard",
    thumbnail: "/placeholder.svg?height=400&width=600&text=Product+Roadmap",
    createdAt: "2023-11-15T10:30:00Z",
    updatedAt: "2023-12-01T14:45:00Z",
    starred: true,
    collaborators: [
      { name: "Alex Johnson", initials: "AJ", avatar: "/placeholder.svg?height=32&width=32&text=AJ" },
      { name: "Maria Garcia", initials: "MG", avatar: "/placeholder.svg?height=32&width=32&text=MG" },
      { name: "David Kim", initials: "DK", avatar: "/placeholder.svg?height=32&width=32&text=DK" },
    ],
    elements: [],
  },
  {
    id: "2",
    title: "Website Redesign Wireframes",
    description: "UI/UX wireframes for the company website redesign project",
    type: "wireframe",
    thumbnail: "/placeholder.svg?height=400&width=600&text=Website+Wireframes",
    createdAt: "2023-10-20T09:15:00Z",
    updatedAt: "2023-11-28T16:20:00Z",
    starred: false,
    collaborators: [
      { name: "Sarah Chen", initials: "SC", avatar: "/placeholder.svg?height=32&width=32&text=SC" },
      { name: "James Wilson", initials: "JW", avatar: "/placeholder.svg?height=32&width=32&text=JW" },
    ],
    elements: [],
  },
  {
    id: "3",
    title: "Marketing Campaign Flow",
    description: "Customer journey and campaign flow for Q1 marketing initiatives",
    type: "flowchart",
    thumbnail: "/placeholder.svg?height=400&width=600&text=Marketing+Flow",
    createdAt: "2023-11-05T11:45:00Z",
    updatedAt: "2023-11-25T13:10:00Z",
    starred: true,
    collaborators: [
      { name: "Emily Rodriguez", initials: "ER", avatar: "/placeholder.svg?height=32&width=32&text=ER" },
      { name: "Michael Brown", initials: "MB", avatar: "/placeholder.svg?height=32&width=32&text=MB" },
      { name: "Lisa Wang", initials: "LW", avatar: "/placeholder.svg?height=32&width=32&text=LW" },
    ],
    elements: [],
  },
  {
    id: "4",
    title: "Product Architecture",
    description: "Technical architecture and system design for the new product",
    type: "mindmap",
    thumbnail: "/placeholder.svg?height=400&width=600&text=Product+Architecture",
    createdAt: "2023-09-12T08:30:00Z",
    updatedAt: "2023-11-20T10:15:00Z",
    starred: false,
    collaborators: [
      { name: "Robert Taylor", initials: "RT", avatar: "/placeholder.svg?height=32&width=32&text=RT" },
      { name: "Jennifer Lee", initials: "JL", avatar: "/placeholder.svg?height=32&width=32&text=JL" },
    ],
    elements: [],
  },
  {
    id: "5",
    title: "Team Brainstorming Session",
    description: "Ideas and notes from the quarterly team brainstorming session",
    type: "whiteboard",
    thumbnail: "/placeholder.svg?height=400&width=600&text=Brainstorming",
    createdAt: "2023-11-10T13:00:00Z",
    updatedAt: "2023-11-10T16:30:00Z",
    starred: false,
    collaborators: [
      { name: "Alex Johnson", initials: "AJ", avatar: "/placeholder.svg?height=32&width=32&text=AJ" },
      { name: "Sarah Chen", initials: "SC", avatar: "/placeholder.svg?height=32&width=32&text=SC" },
      { name: "David Kim", initials: "DK", avatar: "/placeholder.svg?height=32&width=32&text=DK" },
      { name: "Emily Rodriguez", initials: "ER", avatar: "/placeholder.svg?height=32&width=32&text=ER" },
    ],
    elements: [],
  },
  {
    id: "6",
    title: "User Onboarding Flow",
    description: "Step-by-step user onboarding process for the mobile app",
    type: "flowchart",
    thumbnail: "/placeholder.svg?height=400&width=600&text=Onboarding+Flow",
    createdAt: "2023-10-05T14:20:00Z",
    updatedAt: "2023-11-15T09:45:00Z",
    starred: true,
    collaborators: [
      { name: "James Wilson", initials: "JW", avatar: "/placeholder.svg?height=32&width=32&text=JW" },
      { name: "Lisa Wang", initials: "LW", avatar: "/placeholder.svg?height=32&width=32&text=LW" },
    ],
    elements: [],
  },
  {
    id: "7",
    title: "Feature Prioritization",
    description: "Feature prioritization matrix for the upcoming development cycle",
    type: "whiteboard",
    thumbnail: "/placeholder.svg?height=400&width=600&text=Feature+Prioritization",
    createdAt: "2023-11-01T10:00:00Z",
    updatedAt: "2023-11-18T11:30:00Z",
    starred: false,
    collaborators: [
      { name: "Michael Brown", initials: "MB", avatar: "/placeholder.svg?height=32&width=32&text=MB" },
      { name: "Jennifer Lee", initials: "JL", avatar: "/placeholder.svg?height=32&width=32&text=JL" },
      { name: "Robert Taylor", initials: "RT", avatar: "/placeholder.svg?height=32&width=32&text=RT" },
    ],
    elements: [],
  },
  {
    id: "8",
    title: "Competitive Analysis",
    description: "Detailed analysis of competitors in the market",
    type: "mindmap",
    thumbnail: "/placeholder.svg?height=400&width=600&text=Competitive+Analysis",
    createdAt: "2023-10-15T09:30:00Z",
    updatedAt: "2023-11-05T15:20:00Z",
    starred: false,
    collaborators: [
      { name: "Maria Garcia", initials: "MG", avatar: "/placeholder.svg?height=32&width=32&text=MG" },
      { name: "David Kim", initials: "DK", avatar: "/placeholder.svg?height=32&width=32&text=DK" },
    ],
    elements: [],
  },
]
